hotel/urls.py
from django.urls import path
from . import views


app_name = 'hotel'

urlpatterns = [
  path("", views.index, name="index"),
  path("sign_up/", views.sign_up, name="sign_up"),
  path("logout", views.logout_user, name="logout"),
  path("login", views.login_user, name="login"),
  path("nutrient/create", views.nutrient_create, name="nutrient_create"),
  path('nutrients_list',views.nutrients_list, name= "nutrients_list"),
  path('nutrient/edit/<int:id>', views.nutrient_edit, name="nutrient_edit"),
  path('nutrient/delete/<int:id>', views.nutrient_destroy, name="nutrient_destroy"),
  path('product/new', views.product_create, name='product_create'),
  path('products_list',views.products_list, name= "products_list"),
  path('product/edit/<int:id>', views.product_edit, name="product_edit"),
  path('product/delete/<int:id>', views.product_destroy, name="product_destroy"),
]

hotel/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Nutrient(models.Model):
    nutrient_name = models.CharField(max_length=50, unique = True)
    nutrient_unit = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.nutrient_name

class Product(models.Model):
    name = models.CharField(max_length=50,unique = True)
    description = models.TextField()
    status = models.BooleanField(default= False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    nutrients = models.ManyToManyField(Nutrient, through="ProductNutrients")

    def __str__(self):
        return self.name

class ProductNutrients(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    nutrient = models.ForeignKey('Nutrient', on_delete=models.PROTECT)
    nutrient_value = models.DecimalField(max_digits=19, decimal_places=10, default= 0.0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        unique_together = ('product', 'nutrient')

    def __str__(self):
        return str(self.nutrient_value)

hotel/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from django.urls import reverse

from .models import Nutrient, Product ,ProductNutrients
from .form import NutrientForm, ProductForm, ProductNutrientsForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView




# Create your views here.
def index(request):
  return render(request = request,
                template_name='hotel/index.html',
                context = {"nutrients":Nutrient.objects.all})


def sign_up(request):
  if request.method == "POST":
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      username = form.cleaned_data.get('username')
      messages.success(request, f"New account created: {username}")
      login(request, user)
      return redirect("hotel:index")
    else:
      for msg in form.error_messages:
        print(form.error_messages[msg])
        messages.error(request, f"{msg}: {form.error_messages[msg]}")

      return render(request=request,
                    template_name="hotel/sign_up.html",
                    context={"form": form})

  form = UserCreationForm
  return render(request = request,
                template_name = "hotel/sign_up.html",
                context={"form":form})


def login_user(request):
  if request.method == 'POST':
    form = AuthenticationForm(request=request, data=request.POST)
    if form.is_valid():
      username = form.cleaned_data.get('username')
      password = form.cleaned_data.get('password')
      user = authenticate(username=username, password=password)
      if user is not None:
        login(request, user)
        messages.info(request, f"You are now logged in as {username}")
        return redirect('/')
      else:
        messages.error(request, "Invalid username or password.")
    else:
      messages.error(request, "Invalid username or password.")
  form = AuthenticationForm()
  return render(request=request,
                template_name="hotel/login.html",
                context={"form": form})

def logout_user(request):
  logout(request)
  messages.info(request, "Logged out successfully!")
  return redirect("hotel:index")

def nutrient_create(request):
  if request.method == 'POST':
    context = {}
    # create object of form
    form = NutrientForm(request.POST or None)
    # check if form data is valid
    if form.is_valid():
      # save the form data to model
      fs = form.save(commit=False)
      fs.updated_by = request.user
      fs.save()
      messages.info(request, f"Nutrient {form.cleaned_data['nutrient_name']} is created.")
      return redirect('/')
    else:
      messages.error(request, "Invalid details")

  form = NutrientForm
  return render(request=request,
                template_name="hotel/nutrient_create.html",
                context={"form": form})

def nutrients_list(request):
    nutrients = Nutrient.objects.all()
    return render(request, "hotel/nutrients_list.html", {'nutrients': nutrients})


def nutrient_edit(request, id):
  if not request.user.is_authenticated:
    messages.info(request, "Please Login to continue.")
    return redirect('/')
  nutrient = Nutrient.objects.get(pk=id)
  if request.method == "GET":
    return render(request, "hotel/nutrient_edit.html", {'nutrient': nutrient})
  else:
    form = NutrientForm(request.POST or None, instance=nutrient)
    if form.is_valid():
      fs = form.save(commit=False)
      fs.updated_by = request.user
      fs.save()
      messages.info(request, f"Nutrient {nutrient.nutrient_name} is updated.")
      return redirect('hotel:nutrients_list')
    return render(request, 'hotel/nutrient_edit.html', {'nutrient': nutrient})


def nutrient_destroy(request, id):
  if not request.user.is_authenticated:
    messages.info(request, "Please Login to continue.")
    return redirect('/')
  nutrient = Nutrient.objects.get(id=id)
  nutrient.delete()
  messages.info(request, f"Nutrient {nutrient.nutrient_name} is deleted.")
  return redirect('hotel:nutrients_list')

def product_create(request):
  if not request.user.is_authenticated:
    messages.info(request, "Please Login to continue.")
    return redirect('/')
  if request.method == 'POST':
    # context = {}
    # # create object of form
    form = ProductForm(request.POST or None)
    product = Product(name= form.data['name'], description= form.data['description'])
    if form.data['status'] == 'True':
      product.status = True
    else:
      product.status = False
    try:
      product.save()
      i = 0
      value = True
      while value:
        pn= ProductNutrients(product=product,nutrient=Nutrient(pk=request.POST[f"basic_attributes[{i}][select]"]),nutrient_value=request.POST[f"basic_attributes[{i}][number]"],updated_by=request.user)
        pn.save()
        i += 1
        try:
          value = request.POST[f"basic_attributes[{i}][select]"]
        except :
          value = False
      messages.info(request, f"Product {form.data['name']} is created.")
      return redirect('/')
    except:
      messages.error(request, "Invalid details")
      return redirect('/')
  else:
    nutrients = Nutrient.objects.all()
    product_form = ProductForm()
    context = {'product_form': product_form, 'nutrients': nutrients}
    return render(request=request,
                  template_name="hotel/product_create.html",
                  context=context)


def products_list(request):
  products = Product.objects.all()
  nutrients ={}
  for product in products:
    nutrients[product.pk] = product.productnutrients_set.all()
  return render(request, "hotel/products_list.html", {'products': products, 'nutrients': nutrients})

def product_edit(request, id):
  if not request.user.is_authenticated:
    messages.info(request, "Please Login to continue.")
    return redirect('/')
  product = Product.objects.get(pk=id)
  product_nutrients= product.productnutrients_set.all()
  nutrients = Nutrient.objects.all()
  if request.method == "GET":
    return render(request, "hotel/product_edit.html", {'product': product, 'product_nutrients': product_nutrients, 'nutrients': nutrients})
  else:
    form = ProductForm(request.POST or None)
    Product.objects.filter(pk=id).update(name=form.data['name'], description=form.data['description'])
    if form.data['status'] == 'True':
      product.status = True
    else:
      product.status = False
    try:
      i = 0
      value = True
      updated = {}
      while value:
        try:
          n_id = request.POST[f"nutrient[{i}][id]"]
          pn = ProductNutrients.objects.get(pk=n_id)
        except:
          n_id = False

        if not n_id:
          pn = ProductNutrients(product=product, nutrient=Nutrient(pk=request.POST[f"basic_attributes[{i}][select]"]),
                                nutrient_value=request.POST[f"basic_attributes[{i}][number]"], updated_by=request.user)
          pn.save()
        else:
          updated[pn.pk] = True
          ProductNutrients.objects.filter(pk=n_id).update(nutrient=Nutrient(pk=request.POST[f"basic_attributes[{i}][select]"]),nutrient_value=request.POST[f"basic_attributes[{i}][number]"],updated_by=request.user)
        i += 1
        try:
          value = request.POST[f"basic_attributes[{i}][select]"]
        except :
          value = False
      messages.info(request, f"Product {form.data['name']} is updated.")
      return redirect('/')
    except:
      messages.error(request, "Invalid details")
    return render(request, "hotel/product_edit.html", {'product': product, 'product_nutrients': product_nutrients, 'nutrients': nutrients})


def product_destroy(request, id):
  if not request.user.is_authenticated:
    messages.info(request, "Please Login to continue.")
    return redirect('/')
  product = Product.objects.get(pk=id)
  product.delete()
  messages.info(request, f"Product {product.name} is deleted.")
  return redirect('hotel:products_list')

hotel/templates/hotel/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Hotel</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script type = "text/javascript" src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
  <script type = "text/javascript" src = "https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
  <script>
<!--      $(document).ready(function() {-->
<!--        $('select').material_select();-->
<!--      });-->
  </script>

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'hotel/style.css' %}">
  <script  src="{% static 'hotel/dist/jquery-nested-form.js' %}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
          <li><a href=#>{{user.username|title}}</a></li>
        {% endif %}
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'hotel:products_list' %}">Products</a></li>
        <li><a href="{% url 'hotel:nutrients_list' %}">Nutrients</a></li>
        {% if user.is_authenticated %}
          <li><a href="/hotel/logout">Logout</a></li>
        {% else %}
          <li><a href="/hotel/login">Login</a></li>
          <li><a href="/hotel/sign_up">SignUp</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'success'%}
              <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
          {% elif message.tags == 'info'%}
              <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
          {% elif message.tags == 'warning'%}
              <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
          {% elif message.tags == 'error'%}
              <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
          {% endif %}
        {% endfor %}
      {% endif %}
    </div>
  </div>
  {% block content %}
  {% endblock %}
</div>

<div class="jumbotron text-center" style="margin-bottom:0">
  <p>Hotel CMS</p>
</div>

</body>
</html>

hotel/templates/hotel/index.html
{% extends 'hotel/header.html' %}

{% block content %}
    <div class="container-fluid">
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'hotel:nutrients_list' %}">All Nutrients</a></li>
          <li><a href="{% url 'hotel:products_list' %}">All Products</a></li>
        {% endif %}
      </ul>
    </div>

{% endblock %}

hotel/templates/hotel/login.html
{% extends 'hotel/header.html' %}

{% block content %}

    <div class="container">
        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
            <button style="background-color:#ADFF2F; color:grey" class="btn btn-outline-info" type="submit">Login</button>
        </form>
        Don't have an account? <a href="/hotel/sign_up" target="blank"><strong>register here</strong></a>!
    </div>
{% endblock %}

hotel/templates/hotel/nutrient_create.html
{% extends 'hotel/header.html' %}

{% block content %}

    <div class="container">
        <form method="POST" action= "{% url 'hotel:nutrient_create' %}">
        {% csrf_token %}
        {{form.as_p}}
            <button style="background-color:#ADFF2F; color:grey" class="btn btn-outline-info" type="submit">Create</button>
        </form>
    </div>
{% endblock %}

hotel/templates/hotel/nutrient_edit.html
{% extends 'hotel/header.html' %}

{% block content %}

<div class="container">
  <div class="form-group row">
      <h5>Update Nutrient</h5>
  </div>
  <form method="POST" action= "{% url 'hotel:nutrient_edit' nutrient.id  %}">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group row">
        <label class="col-form-label">Nutrient Name:</label>
          <input type="text" name="nutrient_name" id="nutrient_name" required maxlength="50" value="{{ nutrient.nutrient_name }}"/>
      </div>
      <div class="form-group row">
        <label class=" col-form-label">Nutrient Unit:</label>
          <input type="text" name="nutrient_unit" id="nutrient_unit" required maxlength="10" value="{{ nutrient.nutrient_unit }}"/>
      </div>
      <div class="form-group row">
        <button style="background-color:#ADFF2F; color:grey" class="btn btn-outline-info" type="submit">Update</button>
      </div>
    </div>
  </form>

</div>
{% endblock %}

hotel/templates/hotel/nutrient_show.html
{% extends 'hotel/header.html' %}

{% block content %}
    <div class="container-fluid">
      <ul>

      </ul>
    </div>

{% endblock %}

hotel/templates/hotel/nutrients_list.html
{% extends 'hotel/header.html' %}

{% block content %}
{% if user.is_authenticated %}
  <center><a href="/hotel/nutrient/create">Create Nutrient</a></center>
  <br><br>
{%endif%}
  <div class="container">
    <table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
      <th>Nutrient Name</th>
      <th>Nutrient Unit</th>
      <th>Nutrient created_at</th>
      <th>Nutrient updated_at</th>
      <th>Nutrient updated_by</th>
      {% if user.is_authenticated %}
        <th>Actions</th>
      {%endif%}
    </tr>
    </thead>
    <tbody>
    {% for nutrie in nutrients %}
      <tr>
        <td>{{ nutrie.nutrient_name }}</td>
        <td>{{ nutrie.nutrient_unit }}</td>
        <td>{{ nutrie.created_at }}</td>
        <td>{{ nutrie.updated_at }}</td>
        <td>{{ nutrie.updated_by }}</td>
        {% if user.is_authenticated %}
          <td>
              <a href="{% url 'hotel:nutrient_edit' nutrie.id %}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
              <a href="/hotel/nutrient/delete/{{ nutrie.id }}">Delete</a>
          </td>
        {%endif%}
      </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<br>
  </div>
{% endblock %}

hotel/templates/hotel/product_create.html
{% extends 'hotel/header.html' %}

{% block content %}

    <p class="container">
      <form method="POST" action= "{% url 'hotel:product_create' %}">
        {% csrf_token %}
        {{product_form.as_p}}
        <h6>Add Nutrients</h6>
        <div id="container">
          <div class="nested-form">
            <p>
              <label for="basic_attributes_0_select"><i class="fa fa-asterisk"></i> Nutrient</label>
              <select class="form-control select_nutrient" name="basic_attributes[0][select]" id="basic_attributes_0_select" required>
                {% for nutrient in nutrients %}
                <option value="{{ nutrient.id }}">{{ nutrient.nutrient_name }}</option>
                {% endfor %}
              </select>
            </p>
            <p>
              <label for="basic_attributes_0_number">Nutrient value:</label>
              <input type="number" name="basic_attributes[0][number]" step="any" required="" id="basic_attributes_0_number", class="form-control">
            </p>
          </div>

        </div>
        <input type="button" value="Add More Nutrient" id="add" class="btn btn-danger" >
        <br><br>

          <button style="background-color:#ADFF2F; color:grey" class="btn btn-outline-info" type="submit">Add Product</button>
        </form>
    </div>
    <script >
      $(document).ready( function () {
        $('#container').nestedForm({
          forms: '.nested-form',
          adder: '#add'
        });
      });
    </script>
{% endblock %}

hotel/templates/hotel/product_edit.html
{% extends 'hotel/header.html' %}

{% block content %}

<div class="container">
  <div class="form-group row">
    <h5>Update Product</h5>
  </div>
  <form method="POST" action= "{% url 'hotel:product_edit' product.id  %}">
    {% csrf_token %}
    <p><label for="id_name">Name:</label>
      <input type="text" name="name" maxlength="50" required="" id="id_name" value="{{product.name}}">
    </p>
    <p><label for="id_description">Description:</label>
      <input type="text" name="description" required="" id="id_description" value="{{product.description}}">
    </p>
    <p>
      <label for="id_status_0">Status:</label>
    </p>
    <ul id="id_status" class="radio_button">
      {%if product.status == True%}
        <li>
          <label for="id_status_0"><input type="radio" name="status" value="True" class="radio_button" required="" id="id_status_0" checked>
          Active</label>
        </li>
        <li>
          <label for="id_status_1"><input type="radio" name="status" value="False" class="radio_button" required="" id="id_status_1">
          Inactive</label>
        </li>
      {%else%}
        <li>
          <label for="id_status_0"><input type="radio" name="status" value="True" class="radio_button" required="" id="id_status_0">
          Active</label>
        </li>
        <li>
          <label for="id_status_1"><input type="radio" name="status" value="False" class="radio_button" required="" id="id_status_1" checked>
          Inactive</label>
        </li>
      {%endif%}

  </ul><p></p>

    <h6>Update Nutrients</h6>
    <div id="container">
      {% for pnutrient in product_nutrients%}
        <div class="nested-form">
          <p>
            <label for={{"basic_attributes_replace_select"|get_string:forloop.counter0}}><i class="fa fa-asterisk"></i> Nutrient</label>
            <select class="form-control select_nutrient" name={{"basic_attributes[replace][select]"|get_string:forloop.counter0}} id={{"basic_attributes_replace_select"|get_string:forloop.counter0}} required>
              {% for nutrient in nutrients %}
                {%if pnutrient.nutrient == nutrient%}
                  <option value="{{ nutrient.id }}" selected>{{ nutrient.nutrient_name }}</option>
                {%else%}
                  <option value="{{ nutrient.id }}" >{{ nutrient.nutrient_name }}</option>
                {%endif%}
              {% endfor %}
            </select>
          </p>
          <p>
            <label for={{"basic_attributes_replace_number"|get_string:forloop.counter0}}>Nutrient value:</label>
            <input type="number" value="{{pnutrient.nutrient_value|floatformat:3}}" name={{"basic_attributes[replace][number]"|get_string:forloop.counter0}} step="any" required="" id={{"basic_attributes_replace_number"|get_string:forloop.counter0}}, class="form-control">
          </p>
        </div>
        <p>
          <input type="hidden" value="{{pnutrient.pk}}" name={{"nutrient[replace][id]"|get_string:forloop.counter0}} id={{"nutrient_replace_id"|get_string:forloop.counter0}}>
        </p>
      {%endfor%}

    </div>
    <input type="button" value="Add More Nutrient" id="add" class="btn btn-danger" >
    <br><br>

    <button style="background-color:#ADFF2F; color:grey" class="btn btn-outline-info" type="submit">Update Product</button>

  </form>
  <script >
      $(document).ready( function () {
        $('#container').nestedForm({
          forms: '.nested-form',
          adder: '#add'
        });
      });
    </script>
</div>
{% endblock %}

hotel/templates/hotel/product_form.html
{% extends 'hotel/header.html' %}

{% block content %}
  <div class="container-fluid">
    <h2>Product</h2>
    <form method="post">{% csrf_token %}
      {{ form.as_p }}

      <h4>Product Nutrients</h4>
      {{ product_nutrients.as_p }}
      <input type="submit" value="Save">
    </form>
  </div>

{% endblock %}


<!--<form method="POST" action= "{% url 'hotel:nutrient_edit' nutrient.id  %}">-->
<!--    {% csrf_token %}-->
<!--    <div class="container">-->
<!--      <br>-->
<!--      <div class="form-group row">-->
<!--        <label class="col-form-label">Nutrient Name:</label>-->
<!--          <input type="text" name="nutrient_name" id="nutrient_name" required maxlength="50" value="{{ nutrient.nutrient_name }}"/>-->
<!--      </div>-->
<!--      <div class="form-group row">-->
<!--        <label class=" col-form-label">Nutrient Unit:</label>-->
<!--          <input type="text" name="nutrient_unit" id="nutrient_unit" required maxlength="10" value="{{ nutrient.nutrient_unit }}"/>-->
<!--      </div>-->
<!--      <div class="form-group row">-->
<!--        <button style="background-color:#ADFF2F; color:grey" class="btn btn-outline-info" type="submit">Update</button>-->
<!--      </div>-->
<!--    </div>-->
<!--  </form>-->

hotel/templates/hotel/products_list.html
{% extends 'hotel/header.html' %}
{% load helper %}
{% block content %}
{% if user.is_authenticated %}
  <center><a href="/hotel/product/new">Create Product</a></center>
  <br><br>
{%endif%}


<div class="container">
  <table class="table table-striped table-bordered table-sm" id="product_table">
    <thead class="thead-dark">
    <tr>
      <th>Product Name</th>
      <th>Product Description</th>
      <th>Product Nutrients</th>
      <th>Product Status</th>
      <th>Product created_at</th>
      <th>Product updated_at</th>
      <th>Product updated_by</th>
      {% if user.is_authenticated %}
        <th>Actions</th>
      {%endif%}
    </tr>
    </thead>
    <tbody>
    {% for product in products %}
    <tr>
      <td>{{ product.name }}{{ product.id }}</td>
      <td>{{ product.description }}</td>
      <td>
        {% for   pnutrient in nutrients|get_item:product.id %}
        {{pnutrient.nutrient.nutrient_name}}: {{pnutrient.nutrient_value|floatformat:3}} {{pnutrient.nutrient.nutrient_unit}}
        <br>
        {%endfor%}
      </td>
      <td>
        {%if product.status%}
        Active
        {%else%}
        Inactive
        {%endif%}
      </td>
      <td>{{ product.created_at }}</td>
      <td>{{ product.updated_at }}</td>
      <td>{{ product.updated_by }}</td>
      {% if user.is_authenticated %}
        <td>
          <a href="{% url 'hotel:product_edit' product.id  %}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
          <a href="/hotel/product/delete/{{ product.id }}">Delete</a>
        </td>
      {%endif%}
    </tr>
    {% endfor %}
    </tbody>
  </table>
  <br>
  <br>
</div>
<script>
  $(document).ready( function () {
    $('#product_table').DataTable({});
  } );
</script>

{% endblock %}

hotel/templates/hotel/sign_up.html
{% extends 'hotel/header.html' %}

{% block content %}
    <br>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button style="background-color:#F4E125; color:grey" class="btn btn-outline-info" type="submit">Sign Up</button>
        </form>
    </div>

    If you already have an account <a href="/hotel/login" target="blank"><strong>login</strong></a> instead.

{% endblock %}